Node.js Span Attributes Hotfix
middleware-dev/docs pull request #285
Opened 2024-04-24 22:56 UTC by lukebarrett24

2024-04-24 23:01 UTC, eduardo-mw requested changes

2024-04-24 23:01 UTC, eduardo-mw commented on apm-configuration/node-js.mdx
> +For any automatically instrumented spans or endpoints, add the following code snippet:
I would just put endpoints. Because you don't instrument spans. Spans are a result of instrumentation

2024-04-25 03:19 UTC, eduardo-mw approved these changes

2024-04-25 03:20 UTC, eduardo-mw requested changes

2024-04-25 03:20 UTC, eduardo-mw commented on apm-configuration/node-js.mdx
> +
Might want to add something isolating/highlighting the `tracker.addAttribute()`

2024-04-25 05:53 UTC, Zamichel approved these changes

2024-04-30 21:05 UTC, Zamichel commented
@eduardo-mw PR waiting on your approval

2024-04-30 21:31 UTC, eduardo-mw approved these changes

2024-04-30 22:40 UTC, merged